# Generated by Django 5.2.8 on 2025-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LOCAL', 'Local User (Home Mirror)'), ('REMOTE', 'Remote Cloud User'), ('CLIENT', 'Client User (Salon)'), ('ADMIN', 'Salon/Admin Manager')], default='LOCAL', max_length=10),
        ),
    ]
